src/Entity/Board.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Groups ;
/**
 * @ORM\Entity(repositoryClass="App\Repository\BoardRepository")
 */
class Board
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"list"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"list","detail"})
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     * @Groups({"list","detail"})
     */
    private $creation_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="boards")
     * @Groups({"list"})
     *
     */
    private $user_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BoardItems", mappedBy="board")
     */
    private $boardItems;

    public function __construct()
    {
        $this->boardItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUserId(): User
    {
        return $this->user_id;
    }

    public function setUserId(User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection|BoardItems[]
     */
    public function getBoardItems(): Collection
    {
        return $this->boardItems;
    }

    public function addBoardItem(BoardItems $boardItem): self
    {
        if (!$this->boardItems->contains($boardItem)) {
            $this->boardItems[] = $boardItem;
            $boardItem->setBoard($this);
        }

        return $this;
    }

    public function removeBoardItem(BoardItems $boardItem): self
    {
        if ($this->boardItems->contains($boardItem)) {
            $this->boardItems->removeElement($boardItem);
            // set the owning side to null (unless already changed)
            if ($boardItem->getBoard() === $this) {
                $boardItem->setBoard(null);
            }
        }

        return $this;
    }
}

templates/Components/BoardsCards.html.twig
<a href="{{ path('boards_view',{'id': key.id}) }}" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
        <div class="col-md-auto">
            <h5 class="mb-1">{{ key.title }}</h5>
        </div>
        <div class="col-md-auto">
            <span class="badge badge-secondary">{{key.creationDate | date('Y-m-d') }}</span>
        </div>
        <div class="col-md-auto">
            <button type="button" class="btn btn-primary">
                Nb Tasks <span class="badge badge-light">{{ key.boardItems | length }}</span>
            </button>
        </div>
        <div class="col-md-auto">

            <form action="{{ path('delete_board',{'id': key.id}) }}" method="post" id="delete">
                <button name="delete"  class="btn btn-danger"><svg class="bi bi-x" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 010 .708l-7 7a.5.5 0 01-.708-.708l7-7a.5.5 0 01.708 0z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 000 .708l7 7a.5.5 0 00.708-.708l-7-7a.5.5 0 00-.708 0z" clip-rule="evenodd"/>
                    </svg>Delete</button>
            </form>
        </div>
    </div>

</a>

templates/Components/NavigationBar.html.twig
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ path('home') }}">Todo App</a>
        </div>
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active" href="{{path('friends')}}">Friends</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Tasks</a>
            </li>
            {% if app.user %}
            <li class="nav-item"><a class="nav-link" href="#">{{ app.user.username }}</a></li>
        </ul>


            <ul class="nav justify-content-end">
                <li class="nav-item"><a href="{{ path('app_logout') }}" class="navbar-link">Logout</a></li>

            </ul>
        {% endif %}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>